name: Test Build Deploy

on:
  push:
    branches: [ "btd" ]
  pull_request:
    branches: [ "btd" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Test
        run: ./gradlew test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Build
        run: ./gradlew build
      - name: Copy jar file to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: esop-trading-0.1-all
          path: build/libs/esop_trading_platform-0.1-all.jar

  deploy:
    name: "Deploying application"
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17


      - name: Download jar file
        uses: actions/download-artifact@v3
        with:
          name: esop-trading-0.1-all
#      - name: download public_ip file
#        run: |
#          aws s3 cp s3://gurukul-preethi/s3-bucket/public_ip.txt public_ip.txt
#          cat public_ip.txt
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: 'us-east-1'

#
#
#      - name: Copy jar file to ec2 instance
#        env:
#            SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
#            SSH_HOST: ${{ needs.terraform.outputs.public_ip }}
#        run: |
#          eval `ssh-agent`
#          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
#          ssh_host=$(cat public_ip.txt | tr -d '"');
#          scp -o StrictHostKeyChecking=no "esop_trading_platform-0.1-all.jar" ec2-user@$SSH_HOST:~
#          ssh -o StrictHostKeyChecking=no ec2-user@$SSH_HOST -t 'sudo yum install java-17-amazon-corretto-headless -y;
#          echo "Installed java";
#          ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts;
#          echo "Host added";
#          pid=$(sudo fuser -v -n tcp 8080);
#          echo "$pid";
#          #!/bin/sh;
#          echo "script";
#          if [ $pid ]
#            then
#            echo "then"
#            sudo fuser -k -n tcp 8080
#            echo "process killed"
#          fi
#          echo "Done with killing";
#          sudo nohup java -jar esop_trading_platform-0.1-all.jar >/dev/null;
#          echo "Process Started"'
#