name: Terraform pipeline

on:
  push:
    branches: [ "terraform" ]
  pull_request:
    branches: [ "terraform" ]

jobs:
  terraform:
    name: "Terraform Pipeline"
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    runs-on: ubuntu-latest
    outputs:
      public_ip: ${{ steps.terraform_output.outputs.public_ip }}

    environment: dev
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.2.0"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Plan
        run: terraform plan


      - name: Terraform Apply final
        run: terraform apply -auto-approve -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Terraform Output
        id: terraform_output
        run: |
          echo "Make directory for IP"
          mkdir ip_add
          cd ip_add
          touch public_ip.txt
          readlink -f public_ip.txt
          echo "file created"
          cd ..
          echo $(terraform output instance_public_ip)
          echo "Save the IP"
          echo $(terraform output instance_public_ip) >> ip_add/public_ip.txt
          echo "Saved the IP in txt file"
          cd ip_add
          echo "Save the IP address in S3 bucket"
          aws s3 sync . s3://gurukul-preethi/s3-bucket
          echo "Uploading is done"
        
        
        
        
#
#  Copy the AWS Credentials:
#    needs: "terraform"
#    uses: KCSPreethi/Micronot-Terrfaorm-implementation/.github/workflows/build.yml
#    secrets:
#      EC2_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
#      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
