name: Terraform pipeline

on:
  push:
    branches: [ "terraform" ]
  pull_request:
    branches: [ "terraform" ]

jobs:
  terraform:
    name: "Terraform Pipeline"
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    runs-on: ubuntu-latest
    outputs:
      public_ip: ${{ steps.terraform_output.outputs.public_ip }}

    environment: dev
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.2.0"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Plan
        run: terraform plan


      - name: Terraform Apply final
        run: terraform apply -auto-approve -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Terraform Output
        id: terraform_output
        run: |
          cd terraform/aws_instance
          touch public_ip.txt
          echo $(terraform output instance_public_ip) >> public_ip.txt
          - name: Copy ip address to artifacts
          uses: actions/upload-artifact@v3
          with:
          name: public_ip
          path: terraform/aws_instance/public_ip.txt
  Copy the artifacts:
          needs: "terraform"
          uses: KCSPreethi/Micronot-Terrfaorm-implementation/.github/workflows/build.yml@/preethi
          secrets:
            EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          with:
            public_ip: ${{ needs.terraform.outputs.public_ip }}